# Generated by Django 2.2.17 on 2026-02-19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0021_protein_family_classification'),
        ('structure', '0049_structuremodel_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptorSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.PositiveSmallIntegerField()),
                ('similarity', models.PositiveSmallIntegerField()),
                ('protein_ref', models.ForeignKey(db_column='ref', on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_ref', to='protein.Protein')),
                ('protein_target', models.ForeignKey(db_column='target', on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_target', to='protein.Protein')),
                ('ref_class', models.ForeignKey(blank=True, db_column='ref_class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_as_ref_class', to='protein.ProteinFamily')),
                ('target_class', models.ForeignKey(blank=True, db_column='target_class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_as_target_class', to='protein.ProteinFamily')),
            ],
            options={
                'db_table': 'classification_receptorsimilarity',
            },
        ),
        migrations.CreateModel(
            name='StructureSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('distance_normalized', models.FloatField(default=0.0)),
                ('protein_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
                ('protein_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
                ('structure_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
                ('structure_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.ProteinState')),
            ],
            options={
                'db_table': 'classification_structuresimilarity',
            },
        ),
        # ReceptorSimilarity indexes/constraints
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['ref_class', 'target_class', 'identity'], name='crs_cls_id_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['ref_class', 'target_class', 'similarity'], name='crs_cls_sim_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['target_class', 'ref_class', 'identity'], name='crs_cls_id_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['target_class', 'ref_class', 'similarity'], name='crs_cls_sim_rev_idx'),
        ),
        migrations.AddConstraint(
            model_name='receptorsimilarity',
            constraint=models.UniqueConstraint(fields=('protein_ref', 'protein_target'), name='crs_uniq_pair'),
        ),
        migrations.AddConstraint(
            model_name='receptorsimilarity',
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, protein_ref=django.db.models.expressions.F('protein_target')),
                name='crs_ref_ne_target',
            ),
        ),
        # StructureSimilarity indexes/constraints
        migrations.AddIndex(
            model_name='structuresimilarity',
            index=models.Index(fields=['state', 'protein_ref', 'protein_target'], name='css_state_prot_pair_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarity',
            index=models.Index(fields=['state', 'structure_ref', 'structure_target'], name='css_state_struct_pair_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarity',
            index=models.Index(fields=['distance'], name='css_dist_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarity',
            index=models.Index(fields=['distance_normalized'], name='css_distn_idx'),
        ),
        migrations.AddConstraint(
            model_name='structuresimilarity',
            constraint=models.UniqueConstraint(fields=('state', 'structure_ref', 'structure_target'), name='css_uniq_state_pair'),
        ),
        migrations.AddConstraint(
            model_name='structuresimilarity',
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, structure_ref=django.db.models.expressions.F('structure_target')),
                name='css_ref_ne_target',
            ),
        ),
    ]

