# Generated by Django 2.2.17 on 2026-02-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_similarity_models'),
        ('protein', '0021_protein_family_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[('sequence', 'Sequence'), ('structure_active', 'Structure (active)'), ('structure_inactive', 'Structure (inactive)')], db_index=True, max_length=32)),
                ('plot_type', models.CharField(choices=[('tsne', 't-SNE')], db_index=True, default='tsne', max_length=16)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
            ],
            options={
                'db_table': 'classification_clustercoord',
            },
        ),
        migrations.AddIndex(
            model_name='clustercoord',
            index=models.Index(fields=['dataset_type', 'plot_type'], name='ccoord_ds_plot_idx'),
        ),
        migrations.AddIndex(
            model_name='clustercoord',
            index=models.Index(fields=['protein', 'dataset_type'], name='ccoord_prot_ds_idx'),
        ),
        migrations.AddConstraint(
            model_name='clustercoord',
            constraint=models.UniqueConstraint(fields=('protein', 'dataset_type', 'plot_type'), name='ccoord_uniq_prot_dataset_plot'),
        ),
    ]

