# Generated by Cursor on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0002_clustercoord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clustercoord",
            name="plot_type",
            field=models.CharField(
                choices=[("tsne", "t-SNE"), ("pca_tsne", "PCA→t-SNE")],
                db_index=True,
                default="tsne",
                max_length=16,
            ),
        ),
    ]

