# Generated by Django 2.2.17 on 2026-02-05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0021_protein_family_classification'),
        ('structure', '0049_structuremodel_model_type'),
        ('alignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptorSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.PositiveSmallIntegerField()),
                ('similarity', models.PositiveSmallIntegerField()),
                ('protein_ref', models.ForeignKey(db_column='ref', on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_ref', to='protein.Protein')),
                ('protein_target', models.ForeignKey(db_column='target', on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_target', to='protein.Protein')),
                ('ref_class', models.ForeignKey(blank=True, db_column='ref_class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_as_ref_class', to='protein.ProteinFamily')),
                ('target_class', models.ForeignKey(blank=True, db_column='target_class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_as_target_class', to='protein.ProteinFamily')),
            ],
            options={
                'db_table': 'alignment_receptorsimilarity',
            },
        ),
        migrations.CreateModel(
            name='StructureSimilarityActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('distance_normalized', models.FloatField(default=0.0)),
                ('protein_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
                ('protein_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
                ('structure_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
                ('structure_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
            ],
            options={
                'db_table': 'alignment_structuresimilarityactive',
            },
        ),
        migrations.CreateModel(
            name='StructureSimilarityInactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('distance_normalized', models.FloatField(default=0.0)),
                ('protein_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
                ('protein_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
                ('structure_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
                ('structure_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
            ],
            options={
                'db_table': 'alignment_structuresimilarityinactive',
            },
        ),
        # ReceptorSimilarity indexes/constraints
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['ref_class', 'target_class', 'identity'], name='rs_cls_id_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['ref_class', 'target_class', 'similarity'], name='rs_cls_sim_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['target_class', 'ref_class', 'identity'], name='rs_cls_id_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['target_class', 'ref_class', 'similarity'], name='rs_cls_sim_rev_idx'),
        ),
        migrations.AddConstraint(
            model_name='receptorsimilarity',
            constraint=models.UniqueConstraint(fields=('protein_ref', 'protein_target'), name='uniq_receptor_similarity_pair'),
        ),
        migrations.AddConstraint(
            model_name='receptorsimilarity',
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, protein_ref=django.db.models.expressions.F('protein_target')),
                name='check_ref_ne_target',
            ),
        ),
        # StructureSimilarityActive indexes/constraints
        migrations.AddIndex(
            model_name='structuresimilarityactive',
            index=models.Index(fields=['protein_ref', 'protein_target'], name='ss_active_prot_pair_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarityactive',
            index=models.Index(fields=['structure_ref', 'structure_target'], name='ss_active_struct_pair_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarityactive',
            index=models.Index(fields=['distance'], name='ss_active_dist_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarityactive',
            index=models.Index(fields=['distance_normalized'], name='ss_active_distn_idx'),
        ),
        migrations.AddConstraint(
            model_name='structuresimilarityactive',
            constraint=models.UniqueConstraint(fields=('structure_ref', 'structure_target'), name='uniq_structsim_active_pair'),
        ),
        migrations.AddConstraint(
            model_name='structuresimilarityactive',
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, structure_ref=django.db.models.expressions.F('structure_target')),
                name='check_structsim_active_ref_ne_target',
            ),
        ),
        # StructureSimilarityInactive indexes/constraints
        migrations.AddIndex(
            model_name='structuresimilarityinactive',
            index=models.Index(fields=['protein_ref', 'protein_target'], name='ss_inactive_prot_pair_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarityinactive',
            index=models.Index(fields=['structure_ref', 'structure_target'], name='ss_inactive_struct_pair_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarityinactive',
            index=models.Index(fields=['distance'], name='ss_inactive_dist_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarityinactive',
            index=models.Index(fields=['distance_normalized'], name='ss_inactive_distn_idx'),
        ),
        migrations.AddConstraint(
            model_name='structuresimilarityinactive',
            constraint=models.UniqueConstraint(fields=('structure_ref', 'structure_target'), name='uniq_structsim_inactive_pair'),
        ),
        migrations.AddConstraint(
            model_name='structuresimilarityinactive',
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, structure_ref=django.db.models.expressions.F('structure_target')),
                name='check_structsim_inactive_ref_ne_target',
            ),
        ),
    ]

