# Generated by Django 2.2.17 on 2025-07-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0020_auto_20250318_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='sense',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
