# Generated by Django 2.2.17 on 2026-07-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0021_protein_family_classification'),
        ('protein', '0022_auto_20260310_1709'),
    ]

    operations = [
    ]
